version: "3.10"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    env_file: .env
    volumes: 
      - ./src:/code
    ports:
      - 8000:8000
    networks:
      shortener:
        aliases:
          - shortener-app

  redis:
    image: redis
    env_file: .env
    volumes:
      - ./redis_data:/data
    expose:
      - 6379
    networks:
      shortener:
        aliases:
          - shortener-redis

networks:
  shortener:
    external: true
